/**
 * The other names people call these by.
 *
 * From a review of a much larger app: 「기구마다 이름이 달라서 초보자인데 어플에
 * 나온 운동 이름만 보고 찾는데 기구와 이름이 다르니 찾기가 어렵네요 ㅠ 다른
 * 이름들도 같이 있으면 기구 찾기 수월할 거 같아요」. A catalogue that answers to
 * exactly one spelling is a catalogue that looks empty to anyone who learned
 * the movement somewhere else — from a trainer, from a sticker on a machine,
 * from English, or from a friend who says 랫풀.
 *
 * Three kinds of alias live here, and all three come from how people actually
 * type rather than from how the movement is properly named:
 *
 *   the English            bench press, squat, deadlift
 *   the short form         랫풀, 벤치, 데드, 오버헤드
 *   the other Korean       턱걸이 for 풀업, 종아리 for 카프 레이즈, 딥 for 딥스
 *
 * These are only ever *extra* ways in. The name on the card never changes, so
 * nobody has to learn a second vocabulary to read their own history back.
 */

export const ALIASES: Record<string, string[]> = {
  벤치프레스: ['bench press', '벤치', '플랫 벤치', '가슴 기계'],
  '인클라인 벤치프레스': ['incline bench press', '인클라인 벤치', '윗가슴'],
  '디클라인 벤치프레스': ['decline bench press', '디클라인 벤치', '아랫가슴'],
  '덤벨 프레스': ['dumbbell press', '덤벨 벤치', '덤벨 체스트 프레스'],
  '인클라인 덤벨 프레스': ['incline dumbbell press', '인클라인 덤벨'],
  '체스트 프레스 머신': ['chest press', '체스트 프레스', '가슴 머신'],
  '케이블 크로스오버': ['cable crossover', '케이블 플라이', '크로스오버'],
  '펙덱 플라이': ['pec deck', '펙덱', '버터플라이', '나비 머신'],
  푸시업: ['push up', 'pushup', '팔굽혀펴기', '팔굽혀 펴기'],

  데드리프트: ['deadlift', '데드'],
  '루마니안 데드리프트': ['romanian deadlift', 'rdl', '루마니안', '루디'],
  '바벨 로우': ['barbell row', '벤트오버 로우', '바벨로우'],
  '티바 로우': ['t-bar row', 't바 로우', '티바'],
  '랫 풀다운': ['lat pulldown', '랫풀다운', '랫풀', '등 기계'],
  '시티드 로우': ['seated row', '시티드로우', '케이블 로우'],
  풀업: ['pull up', 'pullup', '턱걸이'],
  친업: ['chin up', 'chinup', '언더 턱걸이'],
  '원암 덤벨 로우': ['one arm dumbbell row', '원암 로우', '한팔 덤벨 로우'],
  '백 익스텐션': ['back extension', '백익스텐션', '허리 신전', '척추기립근'],
  슈러그: ['shrug', '슈럭', '승모근'],

  '오버헤드 프레스': ['overhead press', 'ohp', '밀리터리 프레스', '숄더 프레스'],
  '덤벨 숄더 프레스': ['dumbbell shoulder press', '덤벨 어깨', '숄더 프레스'],
  '아놀드 프레스': ['arnold press', '아놀드'],
  '사이드 레터럴 레이즈': ['lateral raise', '레터럴 레이즈', '사레레', '측면 삼각근'],
  '프론트 레이즈': ['front raise', '전면 레이즈'],
  '리어 델트 플라이': ['rear delt fly', '리어 델트', '후면 삼각근', '리어 레이즈'],
  '페이스 풀': ['face pull', '페이스풀'],
  '업라이트 로우': ['upright row', '업라이트로우'],

  스쿼트: ['squat', '바벨 스쿼트', '백 스쿼트'],
  '레그 프레스': ['leg press', '레그프레스', '다리 기계'],
  '레그 익스텐션': ['leg extension', '레그익스텐션', '대퇴사두 기계'],
  '레그 컬': ['leg curl', '레그컬', '햄스트링 기계', '시티드 레그컬'],
  런지: ['lunge'],
  '불가리안 스플릿 스쿼트': ['bulgarian split squat', '불가리안', '스플릿 스쿼트'],
  '힙 쓰러스트': ['hip thrust', '힙쓰러스트', '엉덩이', '둔근'],
  '카프 레이즈': ['calf raise', '카프레이즈', '종아리'],
  스텝업: ['step up', '스텝 업'],
  '점프 스쿼트': ['jump squat', '점프스쿼트'],
  '월 싯': ['wall sit', '월싯', '벽 스쿼트'],
  'AB 슬라이드': ['ab slide', 'ab wheel', 'ab roller', '에이비 슬라이드', '복근 슬라이드', '복근 롤러', '앱 롤러', '롤아웃', '휠 롤아웃'],
  '사이드 플랭크': ['side plank', '옆 플랭크'],
  '밴드 로우': ['band row', '밴드', '튜빙 로우'],
  '밴드 풀 어파트': ['band pull apart', '풀어파트', '밴드 벌리기'],
  '케틀벨 고블릿 스쿼트': ['kettlebell goblet squat', '고블릿 스쿼트', '케틀벨 스쿼트'],
  '푸시업 바 푸시업': ['push up bar', '푸시업 바', '푸쉬업 바', '팔굽혀펴기 바'],
  '케틀벨 스윙': ['kettlebell swing', '케틀벨', '스윙'],
  '글루트 브릿지': ['glute bridge', '브릿지', '엉덩이 들기'],
  '케이블 킥백': ['cable kickback', '글루트 킥백', '킥백', '엉덩이 킥'],
  '힙 어브덕션 머신': ['hip abduction', '어브덕션', '힙 어브덕션', '다리 벌리기'],
  '덩키 킥': ['donkey kick', '동키 킥', '엉덩이 차기'],
  '스모 데드리프트': ['sumo deadlift', '스모 데드', '와이드 데드'],
  굿모닝: ['good morning', '굿모닝 엑서사이즈'],

  '바벨 컬': ['barbell curl', '바벨컬', '이두'],
  '덤벨 컬': ['dumbbell curl', '덤벨컬'],
  '해머 컬': ['hammer curl', '해머컬'],
  '프리처 컬': ['preacher curl', '프리처컬'],
  '케이블 컬': ['cable curl', '케이블컬'],
  '리버스 컬': ['reverse curl', '리버스컬', '전완'],
  '트라이셉스 푸시다운': ['triceps pushdown', '푸시다운', '삼두 푸시다운', '케이블 푸시다운'],
  '오버헤드 트라이셉스 익스텐션': ['overhead triceps extension', '삼두 익스텐션', '프렌치 프레스', '트라이셉스 익스텐션'],
  '트라이셉스 킥백': ['triceps kickback', '킥백'],
  딥스: ['dips', 'dip', '딥'],

  크런치: ['crunch'],
  '윗몸 일으키기': ['sit up', 'situp', '윗몸일으키기'],
  '레그 레이즈': ['leg raise', '레그레이즈'],
  '행잉 레그 레이즈': ['hanging leg raise', '행잉 레그레이즈', '철봉 다리'],
  '바이시클 크런치': ['bicycle crunch', '자전거 크런치'],
  '러시안 트위스트': ['russian twist', '러시안트위스트', '복사근'],
  '마운틴 클라이머': ['mountain climber', '마운틴클라이머'],
  플랭크: ['plank'],

  러닝: ['running', 'run', '달리기', '트레드밀', '런닝머신', '러닝머신'],
  걷기: ['walking', 'walk', '산책', '워킹'],
  줄넘기: ['jump rope', '줄 넘기'],
  '계단 오르기': ['계단'],
  '천국의 계단': ['stairmaster', 'stair climber', 'stepmill', '스텝밀', '천국의계단', '계단 머신'],
  버피: ['burpee', '버피 테스트'],
  수영: ['swimming', 'swim'],
  사이클: ['cycling', 'bike', '자전거', '실내자전거'],
  일립티컬: ['elliptical', '엘립티컬'],
  '로잉 머신': ['rowing machine', 'rower', '로잉', '로워'],
  // Added with the 2026-10-03 movements.
  '덤벨 플라이': ['dumbbell fly', '플라이'],
  '인클라인 덤벨 플라이': ['incline dumbbell fly', '인클라인 플라이'],
  '스미스 머신 벤치프레스': ['smith bench press', '스미스 벤치', '스미스 벤치프레스'],
  '인클라인 체스트 프레스 머신': ['incline chest press', '인클라인 머신', '인클라인 프레스 머신'],
  '디클라인 푸시업': ['decline push up', '발 올려 푸시업'],
  '니 푸시업': ['knee push up', '무릎 푸시업', '무릎 대고 팔굽혀펴기'],
  '덤벨 풀오버': ['dumbbell pullover', '풀오버'],
  '로우 케이블 플라이': ['low cable fly', '로우 투 하이 플라이', '케이블 플라이'],
  '클로즈 그립 벤치프레스': ['close grip bench press', '클로즈 그립 벤치', '내로우 벤치'],
  '어시스트 풀업 머신': ['assisted pull up', '어시스트 풀업', '보조 풀업', '풀업 머신'],
  '스트레이트 암 풀다운': ['straight arm pulldown', '암 풀다운', '스트레이트 암'],
  '클로즈 그립 랫 풀다운': ['close grip lat pulldown', '클로즈 그립 풀다운', '내로우 풀다운'],
  '인버티드 로우': ['inverted row', '호주식 풀업', '바디 로우'],
  '펜들레이 로우': ['pendlay row', '펜들레이'],
  '벤트오버 덤벨 로우': ['bent over dumbbell row', '덤벨 로우', '양손 덤벨 로우'],
  '체스트 서포티드 로우': ['chest supported row', '인클라인 덤벨 로우', '엎드려 로우'],
  '하이 로우 머신': ['high row', '하이 로우', '해머 하이 로우'],
  '랙 풀': ['rack pull', '랙풀'],
  '덤벨 슈러그': ['dumbbell shrug', '덤벨 슈럭'],
  '슈퍼맨': ['superman', '슈퍼맨 자세'],
  '파머스 워크': ['farmers walk', 'farmer carry', '파머스 캐리', '들고 걷기'],
  '숄더 프레스 머신': ['shoulder press machine', '숄더 프레스', '어깨 머신'],
  '스미스 머신 숄더 프레스': ['smith shoulder press', '스미스 숄더 프레스'],
  '케이블 레터럴 레이즈': ['cable lateral raise', '케이블 사레레', '케이블 레터럴'],
  '레터럴 레이즈 머신': ['lateral raise machine', '사레레 머신', '레터럴 머신'],
  '리버스 펙덱 플라이': ['reverse pec deck', '리버스 펙덱', '리어 델트 머신'],
  '파이크 푸시업': ['pike push up', '파이크'],
  '랜드마인 프레스': ['landmine press', '랜드마인'],
  '푸시 프레스': ['push press', '푸시프레스'],
  'Y 레이즈': ['y raise', '와이 레이즈'],
  '프론트 스쿼트': ['front squat', '프론트스쿼트'],
  '핵 스쿼트': ['hack squat', '핵스쿼트', '핵 스쿼트 머신'],
  '스미스 머신 스쿼트': ['smith squat', '스미스 스쿼트'],
  '덤벨 고블릿 스쿼트': ['goblet squat', '고블릿 스쿼트', '고블릿'],
  '덤벨 스쿼트': ['dumbbell squat'],
  '맨몸 스쿼트': ['bodyweight squat', 'air squat', '에어 스쿼트', '맨몸스쿼트'],
  '스플릿 스쿼트': ['split squat'],
  '워킹 런지': ['walking lunge', '워킹런지', '걸으며 런지'],
  '리버스 런지': ['reverse lunge', '뒤로 런지'],
  '사이드 런지': ['side lunge', 'lateral lunge', '옆 런지'],
  '덤벨 루마니안 데드리프트': ['dumbbell rdl', '덤벨 루마니안', '덤벨 루디', '덤벨 데드리프트'],
  '싱글 레그 데드리프트': ['single leg deadlift', '한발 데드', '한발 데드리프트', '원레그 데드'],
  '트랩바 데드리프트': ['trap bar deadlift', 'hex bar deadlift', '트랩바', '헥스바 데드리프트'],
  '시티드 레그 컬': ['seated leg curl', '시티드 레그컬', '앉아서 레그컬'],
  '시티드 카프 레이즈': ['seated calf raise', '앉아서 종아리'],
  '싱글 레그 글루트 브릿지': ['single leg glute bridge', '한발 브릿지', '원레그 브릿지'],
  '케이블 풀 스루': ['cable pull through', '풀 스루', '풀스루'],
  '노르딕 햄스트링 컬': ['nordic curl', 'nordic hamstring curl', '노르딕 컬', '노르딕'],
  '박스 점프': ['box jump', '박스점프'],
  '파워 클린': ['power clean', '클린', '파워클린'],
  '덤벨 스러스터': ['thruster', '스러스터', '쓰러스터'],
  '인클라인 덤벨 컬': ['incline dumbbell curl', '인클라인 컬'],
  '컨센트레이션 컬': ['concentration curl', '컨센 컬', '집중 컬'],
  '이지바 컬': ['ez bar curl', 'ez 컬', '이지바', '이지컬'],
  '암 컬 머신': ['arm curl machine', '암컬 머신', '이두 머신', '프리처 컬 머신'],
  '로프 해머 컬': ['rope hammer curl', '케이블 해머 컬', '로프 컬'],
  '스컬 크러셔': ['skull crusher', 'lying triceps extension', '라잉 트라이셉스 익스텐션', '스컬크러셔'],
  '케이블 오버헤드 트라이셉스 익스텐션': ['cable overhead triceps extension', '케이블 오버헤드 익스텐션', '오버헤드 로프'],
  '벤치 딥스': ['bench dips', '벤치 딥', '의자 딥스'],
  '다이아몬드 푸시업': ['diamond push up', '다이아몬드 팔굽혀펴기', '내로우 푸시업'],
  '트라이셉스 딥 머신': ['triceps dip machine', '딥스 머신', '시티드 딥'],
  '리스트 컬': ['wrist curl', '손목 컬', '전완 컬'],
  '케이블 크런치': ['cable crunch', '로프 크런치'],
  '앱 크런치 머신': ['ab crunch machine', '복근 머신', '앱 머신', '크런치 머신'],
  '리버스 크런치': ['reverse crunch', '리버스크런치'],
  '데드버그': ['dead bug', '데드 버그'],
  '버드독': ['bird dog', '버드 독'],
  '브이 업': ['v up', 'v-up', '브이업', '제트업'],
  '할로우 홀드': ['hollow hold', 'hollow body', '할로우 바디', '할로우'],
  '플러터 킥': ['flutter kick', '플러터킥', '발차기'],
  '토즈 투 바': ['toes to bar', 't2b', '토투바'],
  '케이블 우드찹': ['wood chop', 'cable woodchop', '우드찹', '우드 찹'],
  '인클라인 워킹': ['incline walking', '경사 걷기', '인클라인 걷기', '트레드밀 걷기', '러닝머신 걷기'],
  '등산': ['hiking', '산행', '산'],
  '점핑 잭': ['jumping jack', '팔벌려뛰기', '팔 벌려 뛰기'],
  '하이 니': ['high knees', '제자리 뛰기', '무릎 들어 뛰기'],
  '에어 바이크': ['air bike', 'assault bike', '어썰트 바이크', '에어바이크'],
  '배틀 로프': ['battle rope', '배틀로프', '로프'],
  '섀도 복싱': ['shadow boxing', '쉐도우 복싱', '섀도우 복싱', '복싱'],
};

/** Every extra spelling this movement answers to, or none. */
export function aliasesOf(name: string): string[] {
  return ALIASES[name] ?? [];
}
